[[redirects]]
from = "https://copies.phillydayhiker.com/*"
to = "https://phillydayhiker.com/copies/:splat"
status = 301
force = true

[[redirects]]
from = "/copies/*"
to = "https://copies.netlify.com/:splat"
status = 200
force = true
headers = {X-Forwarded-Host = "www.phillydayhiker.com"}